//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marvin.AppCore.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marvin.AppCore.Globalization.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe outra aplicação ativa cadastrada com o mesmo código.
        /// </summary>
        public static string AlreadyExistsApplicationCode {
            get {
                return ResourceManager.GetString("AlreadyExistsApplicationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe uma váriável de configuração da aplicação com a mesma chave.
        /// </summary>
        public static string AlreadyExistsApplicationSetting {
            get {
                return ResourceManager.GetString("AlreadyExistsApplicationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A chave da aplicação não corresponde com o seu registro. Verifique o arquivo de configuração do sistema.
        /// </summary>
        public static string AppNoMatchKey {
            get {
                return ResourceManager.GetString("AppNoMatchKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O registro da aplicação não foi encontrado. Verifique o arquivo de configuração do sistema.
        /// </summary>
        public static string AppNotFound {
            get {
                return ResourceManager.GetString("AppNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha na autenticação.
        /// </summary>
        public static string AuthenticationFail {
            get {
                return ResourceManager.GetString("AuthenticationFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário inativo.
        /// </summary>
        public static string AuthenticationFail_InactiveUser {
            get {
                return ResourceManager.GetString("AuthenticationFail_InactiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado.
        /// </summary>
        public static string AuthenticationFail_UserNotFound {
            get {
                return ResourceManager.GetString("AuthenticationFail_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha incorreta.
        /// </summary>
        public static string AuthenticationFail_WrongPassword {
            get {
                return ResourceManager.GetString("AuthenticationFail_WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do usuário deve ser informado.
        /// </summary>
        public static string AutheticationFail_UserNameRequired {
            get {
                return ResourceManager.GetString("AutheticationFail_UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código da aplicação não foi definido. Verifique o arquivo de configuração do sistema.
        /// </summary>
        public static string NotDefinedAppCode {
            get {
                return ResourceManager.GetString("NotDefinedAppCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O chave da aplicação não foi definido. Verifique o arquivo de configuração do sistema.
        /// </summary>
        public static string NotDefinedAppKey {
            get {
                return ResourceManager.GetString("NotDefinedAppKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso negado.
        /// </summary>
        public static string Security_AccessForbidden {
            get {
                return ResourceManager.GetString("Security_AccessForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessão Expirada.
        /// </summary>
        public static string Security_SessionTimeout {
            get {
                return ResourceManager.GetString("Security_SessionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nova senha deve ser diferente das ultimas {0} senha(s) utilizada(s).
        /// </summary>
        public static string UserSave_BufferedPassword {
            get {
                return ResourceManager.GetString("UserSave_BufferedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail já foi utilizado no cadastro de outro usuário.
        /// </summary>
        public static string UserSave_EmailAlreadyUsed {
            get {
                return ResourceManager.GetString("UserSave_EmailAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Senha deve ter no mínimo {0} caractere(s).
        /// </summary>
        public static string UserSave_ShortPassword {
            get {
                return ResourceManager.GetString("UserSave_ShortPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome de usuário já foi cadastrado.
        /// </summary>
        public static string UserSave_UserNameAlreadyExist {
            get {
                return ResourceManager.GetString("UserSave_UserNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter pelo menos um Numero, letra Maiuscula, letra Minuscula ou Caracter Especial.
        /// </summary>
        public static string UserSave_WeakPassword {
            get {
                return ResourceManager.GetString("UserSave_WeakPassword", resourceCulture);
            }
        }
    }
}
